name: baseline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.8.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - ext/gaussian-splatting/submodules/diff-gaussian-rasterization
    - ext/gaussian-splatting/submodules/simple-knn
